### ISSUE TITLE
No State persistence

### ISSUE THREAD

**Issue by gokulanv** [2019-Arizona-Opportunity-Hack/Team-15#7]
Form values are not persisted when moving across pages

**Comment by Ebelsire** [comment]
This will be pushed to the next master branch in a few minutes.

**Comment by Ebelsire** [comment]
Okay. The branch was pushed to the github account.

I made the switch that controls the slides too complicated than necessary the first time around. Instead I re-used the switch as a function under the CreateUserPage. This will thus allow any stepscreen to have access to its old data during the previous button hit. This is accomplished by keeping the state within CreateUserPage and passing that state down to whatever the current slide is as the props(props.currentForm). 

One of the Yup(for first screen) was turned off for address line 2 due to it being optional(might need to get rid of that).

**Comment by Ebelsire** [comment]
Text and input boxes have also been set to be centered during view.

I will push out another visual update tomorrow.

**Comment by gokulanv** [comment]
Is this done?

**Comment by Ebelsire** [comment]
Yes the validation is closed.
